apiVersion: v2
name: onecx-test-oidc-ui
version: 0.0.0
description: token-app UI
home: https://github.com/onecx/onecx-test-oidc-ui
keywords:
  - token-app
sources:
  - https://github.com/onecx/onecx-test-oidc-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
